### ISSUE TITLE
tsunami_ch4: Confusion about finite difference implementation

### ISSUE THREAD

**Issue by jfdev001** [fortran-in-action/tsunami#22]
I'm confused about the finite difference scheme in the time loop of `tsunami.f90`.  I think there's an error in the discretization provided in the book.

It is currently defined as 

```fortran
u = u - (u * diff(u) + g * diff(h)) / dx * dt 
```
and using mathematical notation, this is equivalent to

```math
u^{t+1} = u^{t} - \frac{u^{t} \cdot \nabla u^{t} + g \nabla h^{t}}{\Delta x \Delta t}.
```

However, this does not seem to be the right formulation of the finite difference of the governing equation

```math
\frac{\partial u}{\partial t} + u \cdot \nabla u = -g \nabla h,
```

since if we use the forward time discretization---leaving out notation for the space discretization since this is implemented already with the `diff_centered` function aliased as `diff` and represented by $\nabla$ in the notation---then the resulting discretization is 

```math
\frac{u^{t+1} - u^{t}}{\Delta t} + u^{t} \cdot \nabla u^{t} = -g \nabla h^{t},
```

which, after solving for $u^{t+1}$, is equivalent to

```math
u^{t+1} = u^{t} - (u^{t} \cdot \nabla u^{t} + g \nabla h^{t}) \Delta t.
```

These formulations are not equivalent. It's quite possible I made some sort of silly error in my discretization, but nevertheless I thought I'd open an issue since

```math
u^{t} - (u^{t} \cdot \nabla u^{t} + g \nabla h^{t}) \Delta t \neq u^{t} - \frac{u^{t} \cdot \nabla u^{t} + g \nabla h^{t}}{\Delta x \Delta t}
```

**Comment by jfdev001** [comment]
Nevermind. I think the `diff` function body confused me. The `dx` in that body is an array while the `dx` in the time loop is the $\Delta x$.

**Comment by milancurcic** [comment]
Hi Jared, sorry I noticed this late (too many emails from GitHub), but I'm glad you figured it out.

I think the key confusion was that this

```
u = u - (u * diff(u) + g * diff(h)) / dx * dt 
```

is equivalent to this:

```
u = u - ((u * diff(u) + g * diff(h)) / dx) * dt 
```
which is the LHS in your last equation, and not to this:

```
u = u -((u * diff(u) + g * diff(h)) / (dx * dt) 
```
which is the RHS of your last equation.
